[tool.isort]
profile = "black"
line_length = 88
known_third_party = [
    "aioredis",
    "alembic",
    "annotated-types",
    "anyio",
    "argon2-cffi",
    "argon2-cffi-bindings",
    "async-timeout",
    "asyncpg",
    "bcrypt",
    "black",
    "certifi",
    "cffi",
    "click",
    "cryptography",
    "dnspython",
    "email_validator",
    "Faker",
    "fastapi",
    "fastapi-users",
    "greenlet",
    "h11",
    "httpcore",
    "httpx",
    "idna",
    "iniconfig",
    "makefun",
    "Mako",
    "MarkupSafe",
    "mypy-extensions",
    "packaging",
    "passlib",
    "pathspec",
    "platformdirs",
    "pluggy",
    "pwdlib",
    "pycparser",
    "pydantic",
    "pydantic-settings",
    "pydantic_core",
    "PyJWT",
    "pytest",
    "pytest-asyncio",
    "pytest-mock",
    "python-dateutil",
    "python-dotenv",
    "python-multipart",
    "six",
    "sniffio",
    "SQLAlchemy",
    "starlette",
    "typing_extensions",
    "uvicorn"
]
[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
